name: CI
on: [ push ]

jobs:
  build-binaries-unix:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest ]

    name: ${{ matrix.os }}-x64 build
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Configure build with CMake
        shell: bash
        run: |
          mkdir cmake-build-release
          cd cmake-build-release
          cmake .. -DCMAKE_BUILD_TYPE=Release
      - name: Build with CMake
        shell: bash
        working-directory: cmake-build-release
        run: |
          cmake --build . --parallel
      - name: Collect outputs
        shell: bash
        run: |
          mkdir -p outputs/${{ matrix.os }}
          cp cmake-build-release/packer/rucksack-packer outputs/${{ matrix.os }}/rucksack-packer-x64
          cp cmake-build-release/unpacker/rucksack-unpacker outputs/${{ matrix.os }}/rucksack-unpacker-x64
      - name: Upload outputs
        uses: actions/upload-artifact@v2
        with:
          name: rucksack-release-${{ github.sha }}
          path: outputs/*

  build-binaries-windows:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        arch: [ x64, x86 ]
        include:
          - arch: x86
            vs-arch: Win32
          - arch: x64
            vs-arch: x64

    name: ${{ matrix.os }}-${{ matrix.arch }} build
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Configure build with CMake
        shell: bash
        run: |
          mkdir cmake-build-release
          cd cmake-build-release
          cmake .. -DCMAKE_BUILD_TYPE=Release -Thost=x64 -A ${{ matrix.vs-arch }}
      - name: Build with CMake
        shell: bash
        working-directory: cmake-build-release
        run: |
          cmake --build . --parallel --config Release
      - name: Collect outputs
        shell: bash
        run: |
          mkdir -p outputs/${{ matrix.os }}
          cp cmake-build-release/packer/Release/rucksack-packer.exe outputs/${{ matrix.os }}/rucksack-packer-${{ matrix.arch }}.exe
          cp cmake-build-release/unpacker/Release/rucksack-unpacker.exe outputs/${{ matrix.os }}/rucksack-unpacker-${{ matrix.arch }}.exe
      - name: Upload outputs
        uses: actions/upload-artifact@v2
        with:
          name: rucksack-release-${{ github.sha }}
          path: outputs/*
